folio-org/mod-calendar

ramls/calendar.raml

Fix typo. This is possessive its. Search “It’s not its”
This merge is also to test the updated API docs generation facility.

FOLIO-398 tidy 1

---

src/main/java/org/folio/rest/impl/CalendarAPI.java
src/test/java/org/folio/rest/impl/CalendarIT.java

Fix the bug in `mod-calendar`
1. closed PGclient transaction when an error occurred while updating and saving the exceptional period
2. added test for an exceptional period
[MODCAL-35](https://issues.folio.org/browse/MODCAL-35)

MODCAL-35 Error saving an exceptional period

---

descriptors/ModuleDescriptor-template.json
ramls/calendar.raml

Resolves: [MODCAL-45](https://issues.folio.org/browse/MODCAL-45)
Split permissions by HTTP method in module descriptor
Corresponding pull requests:
- https://github.com/folio-org/mod-circulation/pull/284
- https://github.com/folio-org/ui-calendar/pull/194

MODCAL-45 Split permissions by http method

---

Jenkinsfile

Turn on doKubeDeploy option to deploy container to Kubernetes ci environment when snapshot or release.

deploy to kubernetes when master/release

---

src/main/resources/templates/db_scripts/schema.json

During BugFest test Q3.2-2019, it was noticed that /calendar/periods/{servicePointId}
/calculateopening API took over 10 seconds. It turns out the generated db query (see below) was very slow. The BugFest env has over 10K records in table **actual_opening_hours**. We added two indexes to the actual_opening_hours and the query execution time improved from **over 10s to half ms**. This PR is to add those two indexes.
`WITH openings_ids as (SELECT jsonb->>'id' opening_id FROM fs00001000_mod_calendar.openings WHERE jsonb->>'servicePointId' = 'db222815-8557-490a-aae7-e2c19d7e5dce'),closest_open_day as (SELECT aoh1.jsonb->>'actualDay' actual_day FROM fs00001000_mod_calendar.actual_opening_hours aoh1 WHERE aoh1.jsonb->>'openingId' IN (SELECT opening_id FROM openings_ids) AND …

Add indexes to improve calculateopening performance

---

descriptors/ModuleDescriptor-template.json

**Purpose**
Remove redundant permission.
**Approach**
Toggle visibility flag for permission 'calendar.all' in module descriptor.
**Link**
[UICAL-90](https://issues.folio.org/browse/UICAL-90)

UICAL-90 Remove UI permission Calendar: All permissions

---

pom.xml

The update fixes two polymorphic typing issues that are security vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2019-16335
* https://nvd.nist.gov/vuln/detail/CVE-2019-14540
Switch to jackson-bom.
This check shows that it jackson-databind 2.10.0 is actually used:
`mvn dependency:tree -Dverbose -Dincludes=com.fasterxml.jackson.core:jackson-databind`

MODCAL-54: Update jackson to 2.10.0, fixes jackson-databind security.

---

pom.xml
src/main/java/org/folio/rest/impl/CalendarAPI.java
src/main/java/org/folio/rest/service/OpeningsService.java
src/main/java/org/folio/rest/service/impl/OpeningsServiceImpl.java
src/test/java/org/folio/rest/impl/CalendarIT.java

Add validation  to avoid overlap of exceptional periods.  To not allow user create or update exceptional periods with overlapping existing.
Resolves story: https://issues.folio.org/browse/MODCAL-49
- implement validation for creation or update periods to calendar
- implement tests for testing all possible options of overlapping
https://issues.folio.org/browse/MODCAL-49

MODCAL-49 add validation for overlapping of exceptional periods

---

Dockerfile
descriptors/ModuleDescriptor-template.json

Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).

MODCAL-60 FOLIO-2358 manage container memory

---

pom.xml
src/main/java/org/folio/rest/service/impl/ActualOpeningHoursServiceImpl.java

See https://issues.folio.org/browse/MODORDSTOR-161 . mod-calendar can fix
the pg_catalog.pg_trgm issue because it is the first upgraded module on
https://github.com/folio-org/platform-core/blob/q2-2020/install.json
CalendarIT.testGetCalendarPeriodsCalculateOpening() uses a service point id
that contains single quotes to test whether there are any SQL injection
issues. To fix these issues ActualOpeningHoursServiceImpl is changed to use
parameterized SQL queries with $1, $2, ... placeholders.

MODCAL-78: RMB 30.2.3, fixing pg_catalog.pg_trgm and sql injection

---

Dockerfile
Jenkinsfile
pom.xml

- upgrade to jdk 11;
- upgrade RMB to 31.0.2
Resolves: [MODCAL-81](https://issues.folio.org/browse/MODCAL-81)

MODCAL-81 update RMB version, use jdk 11

---

src/main/resources/templates/db_scripts/schema.json

RMB is now truncating b-tree indexes to 600 characters. As a result, new indexes are not being picked up by Postgres when it runs queries in mod-calendar. 
Resolves: [MODCAL-72](https://issues.folio.org/browse/MODCAL-72)
The truncating was disabled and now it exceeds maximum 2712 for index. 
'actualDay' contains Date and 'openingId' UUID value, so this means that such limit will not be achievable for these types of values.

MODCAL-72 Disable char truncation for indexes

---

pom.xml

[MODCAL-99](https://issues.folio.org/browse/MODCAL-99)
Upgrade to RMB 33.0.4 which includes Log4j version with CVE-2021-44228 vulnerability fixed.

MODCAL-99 Upgrade to RMB 33.0.4 and Log4j 2.16.0

---

pom.xml

In the scope of the task on module upgrade, proper actions were fulfilled following instructions to update RMB
•	Updated RMB version
•	Updated Vertx version
•	Removed FOLIO fork of the vertx-sql-client and vertx-pg-client
https://issues.folio.org/browse/MODCAL-102
https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md

MODCAL-102 Update RMB to v33.2.4

---

pom.xml

Upgrade postgresql JDBC client from 42.3.3 to 42.5.0. This fixes SQL Injection: https://nvd.nist.gov/vuln/detail/CVE-2022-31197
Note that postgresql 42.3.* and 42.4.* have reached their end-of-life and should no longer be used in production: https://jdbc.postgresql.org/download/
Upgrade snakeyaml from 1.29 to 1.33 fixing Denial of Service (DoS) and Stack-based Buffer Overflow: https://nvd.nist.gov/vuln/detail/CVE-2022-25857
https://nvd.nist.gov/vuln/detail/CVE-2022-38749
https://nvd.nist.gov/vuln/detail/CVE-2022-38751
https://nvd.nist.gov/vuln/detail/CVE-2022-38752
https://nvd.nist.gov/vuln/detail/CVE-2022-41854
Upgrade rest-assured from 4.4.0 to 4.5.1 because Spring Boot uses rest-assured-bom that exists for 4.5.0 and later but not for 4.4.0.
Upgrade folio-spring-base from 4.0.0 (Morning …

MODCAL-119: Spring Boot 2.7.5, folio-spring-base 5.0.2, … fix vulns

---

NEWS.md
src/main/resources/db/changes/0060-drop-rmb-functions.yaml

These were missed as part of the initial upgrade to 2.0.0; these functions were unused.

MODCAL-118: Remove remaining RMB functions 

---

NEWS.md
src/main/resources/db/changes/0060-drop-rmb-functions.yaml

#152 did not fully qualify all function names to the necessary extent, causing errors on liquibase migration.  This PR fixes this issue and resolves the issues caused in 2.2.0.

MODCAL-120: Fix improper migration caused by regression in MODCAL-118

---

src/main/java/org/folio/calendar/domain/mapper/ExceptionHourMapper.java
src/main/java/org/folio/calendar/domain/mapper/ExceptionRangeMapper.java
src/main/java/org/folio/calendar/domain/mapper/NormalOpeningMapper.java
src/main/java/org/folio/calendar/service/CustomTenantService.java
src/main/java/org/folio/calendar/utils/DateUtils.java
src/main/java/org/folio/calendar/utils/PeriodUtils.java
src/test/java/org/folio/calendar/integration/migration/NormalMigrationTest.java
src/test/java/org/folio/calendar/testconstants/Calendars.java
src/test/java/org/folio/calendar/testconstants/ExceptionRanges.java
src/test/java/org/folio/calendar/testconstants/Periods.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsCalendarConversionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsConflictedOrphanExceptionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsExceptionalCalendarConversionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsExceptionalTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsNullConversionTest.java
src/test/resources/database-migrate-data.sql

In mod-calendar v1.15.0 and prior, calendars with normal hours and exceptions were both stored separately, although as the same "period" datatype.  As part of 2.0.0, migration code was introduced to convert the old format to the new format, where calendars contain exceptions; however, this was implemented incorrectly.  The previous logic would mistakenly convert exceptional periods to their own calendars (with no normal openings), resulting in conflicts when the normal hours and the exceptions were both added separately.
This was resolved by restructuring how periods are converted to calendars; the bulk of this is the `toCalendars` method in `PeriodUtils`.  Also included in this PR is a slew of test additions, to ensure this issue cannot resurface.

MODCAL-124: Fix issue with legacy exceptions not associating with calendars

---

src/main/java/org/folio/calendar/utils/CalendarUtils.java
src/test/java/org/folio/calendar/testconstants/Dates.java
src/test/java/org/folio/calendar/unit/utils/CalendarUtilsSurroundingOpeningsTest.java

Under proper circumstances, a request to /calendar/dates/{servicePointId}/surrounding-openings would result in a 500 error with an exception stating that the "key is out of range".
This was due to a logical fault in the CalendarUtils class; when calculating the previous and next openings, sublists of a larger TreeMap were used, however, these sublists had a hard limit on their upper/lower bounds.  Therefore, when slicing calendars into individual dates to fill this map, it was possible for the code to attempt to insert a date which was out of the map's range (therefore on the wrong side of the requested date, making it irrelevant to the query, but still throwing an exception).  This was resolved by adding an extra filter to ensure only necessary dates were considered.

MODCAL-125: Fix surrounding openings calculation edge case

---

.github/workflows/api-doc.yml
.github/workflows/api-lint.yml
Jenkinsfile
README.md
src/main/resources/api/calendar.yaml

Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).

FOLIO-3678 MODCAL-127 Use GitHub Workflows api-lint and api-doc

---

descriptors/ModuleDescriptor-template.json

mod-calendar occasionally runs out of memory in snapshot, resulting in OOM kills. This adds 200 mb as a precaution against this.

[MODCAL-134] Increase default memory

---

src/main/resources/application.yaml

The module can fail to insert sample calendars if the database is quickly created, dropped, and created again in quick succession (less than a few seconds).
```sh
curl --request POST \
--url http://localhost:8081/_/tenant \
--header 'content-type: application/json' \
--header 'x-okapi-tenant: something' \
--data '{ "module_to": "foo", "parameters": [{"key": "loadReference","value": "true"},{"key": "loadSample","value": "true"}]}'
curl --request POST \
--url http://localhost:8081/_/tenant \
--header 'content-type: application/json' \
--header 'x-okapi-tenant: something' \
--data '{ "module_from": "foo", "purge": true }'
curl --request POST \
--url http://localhost:8081/_/tenant \
--header 'x-okapi-tenant: something' \
--header 'content-type: application/json' \
--data '{ "module_to": …
```

[MODCAL-135] Disable server-side caching of prepared queries to handle recreated DBs on the fly

---

descriptors/ModuleDescriptor-template.json
pom.xml

Added Module Descriptor error checker to pom.xml file and applied changes to the module descriptor based on the errors detected. See [MODCAL-136](https://folio-org.atlassian.net/issues/MODCAL-136?jql=ORDER%20BY%20created%20DESC) for relevant links and error checker implementation/usage.

MODCAL-136: Fixed Module Descriptor

---

Dockerfile
Jenkinsfile
NEWS.md
docs/database-schema.md
pom.xml
src/main/java/org/folio/calendar/controller/ApiExceptionHandler.java
src/main/java/org/folio/calendar/controller/CalendarController.java
src/main/java/org/folio/calendar/domain/entity/Calendar.java
src/main/java/org/folio/calendar/domain/sample/SampleCalendars.java
src/main/java/org/folio/calendar/utils/PeriodUtils.java
src/main/resources/application.yaml
src/test/java/org/folio/calendar/integration/BaseApiAutoDatabaseTest.java
src/test/java/org/folio/calendar/integration/BaseApiTest.java
src/test/resources/application.yaml

This updates Java from 17 to 21. As part of this, we had to:
1. Update Spring and friends
1. Change our embedded database architecture for integration tests, due to incompatibility with later Spring/Hibernate
1. Ensure Hibernate is the only one generating entity IDs, to go with new behavior introduced in part of our updates

[FOLIO-4249] Update to Java 21
