folio-org/mod-calendar

ramls/calendar.raml
ramls/examples/opening_collection_get.json
ramls/examples/opening_get.json
ramls/schemas/OpeningCollection.json

The raml-cop was reporting various issues.

FOLIO-601 fix raml

---

src/main/java/org/folio/rest/impl/CalendarAPI.java

Change GET and POST `/calendar/periods/{servicePointId}/period` endpoints according to the principles described in [UICIRC-178](https://issues.folio.org/browse/UICIRC-178)
[MODCAL-31](https://issues.folio.org/browse/MODCAL-31)

MODCAL-31 Change GET and POST endpoints to respect the timezone chosen for the tenant

---

src/main/java/org/folio/rest/impl/CalendarAPI.java
src/test/java/org/folio/rest/impl/CalendarIT.java

Fix the bug in `mod-calendar`
1. Fixed period deletion logic
2. Updated tests
[MODCAL-36](https://issues.folio.org/browse/MODCAL-36)

MODCAL-36 The created period or exception period is not deleted in mod-calendar

---

src/main/java/org/folio/rest/impl/CalendarAPI.java
src/test/java/org/folio/rest/impl/CalendarIT.java

Fix the bug in `mod-calendar`
1. Fixed the logic of obtaining periods
2. Updated tests
[MODCAL-37](https://issues.folio.org/browse/MODCAL-37)

MODCAL-37 Bug API GET: /periods/{servicePointId}/period related to getting more than one period

---

pom.xml
src/main/java/org/folio/rest/impl/CalendarAPI.java

**Purpose**
Fix module freeze
**Approach**
1. Update the 'raml-module-builder' version in pom.xml
2. Apply an updated version of the 'saveBatch()' method
**Link** 
[MODCAL-40](https://issues.folio.org/browse/MODCAL-40)

MODCAL-40 Investigate mod-calendar module freeze

---

pom.xml
src/main/java/org/folio/rest/impl/CalendarAPI.java
src/main/java/org/folio/rest/service/ActualOpeningHoursService.java
src/main/java/org/folio/rest/service/impl/ActualOpeningHoursServiceImpl.java
src/main/java/org/folio/rest/service/impl/OpeningsServiceImpl.java
src/main/java/org/folio/rest/service/impl/RegularHoursServiceImpl.java

jackson-databind >= 2.0.0, <2.9.9
RMB version up to 24.0.0

Fix security vulnerabilities reported

---

src/main/java/org/folio/rest/impl/CalendarAPI.java

**Purpose**
Fix a bug in `mod-calendar`
**Link**
[MODCAL-53](https://issues.folio.org/browse/MODCAL-53)

MODCAL-53 Fix TestTimedOutException for MODCAL-49

---

src/main/java/org/folio/rest/service/impl/ActualOpeningHoursServiceImpl.java

Update SQL request to fix performance issue.
Resolves: [MODCAL-70](https://issues.folio.org/browse/MODCAL-70)
https://issues.folio.org/browse/MODCAL-70

MODCAL-70 fix performance issue

---

pom.xml
src/main/java/org/folio/rest/impl/CalendarAPI.java
src/main/java/org/folio/rest/service/ActualOpeningHoursService.java
src/main/java/org/folio/rest/service/OpeningsService.java
src/main/java/org/folio/rest/service/RegularHoursService.java
src/main/java/org/folio/rest/service/impl/ActualOpeningHoursServiceImpl.java
src/main/java/org/folio/rest/service/impl/OpeningsServiceImpl.java
src/main/java/org/folio/rest/service/impl/RegularHoursServiceImpl.java
src/test/java/org/folio/rest/impl/CalculateOpeningIT.java

1. Update to RMB v30
2. Update vertx to 3.9.0
3. Do all related changes according to RMB upgrading notes
Resolves: [MODCAL-74](https://issues.folio.org/browse/MODCAL-74)

MODCAL-74 update RMB and vertx version

---

pom.xml
src/main/java/org/folio/rest/utils/CalendarUtils.java

Update RMB version to 31.1.5 and Vertx to 3.9.4
Resolves: https://issues.folio.org/browse/MODCAL-83

MODCAL-83 Upgrade RMB and vertx versions

---

pom.xml
src/main/java/org/folio/rest/impl/CalendarAPI.java
src/main/java/org/folio/rest/utils/CalendarUtils.java
src/test/java/org/folio/rest/impl/CalculateOpeningIT.java
src/test/java/org/folio/rest/impl/CalendarIT.java
src/test/java/org/folio/rest/impl/EmbeddedPostgresBase.java

Resolves [MODCAL-90](https://issues.folio.org/browse/MODCAL-90)

[MODCAL-90] Update to RMB 33.0.0

---

NEWS.md
pom.xml

Resolves [MODCAL-92](https://issues.folio.org/browse/MODCAL-92).

[MODCAL-92] Release 1.12.0

---

pom.xml

MODCAL-110: Assorted version upgrades

---

NEWS.md
pom.xml

MODCAL-117: Release v2.0.0

---

NEWS.md
pom.xml

Release v2.1.0 with dependency updates

Release v2.1.0

---

descriptors/DeploymentDescriptor-template.json

As with pretty much all other modules.

Local deployment descriptor

---

src/main/java/org/folio/calendar/domain/mapper/ExceptionHourMapper.java
src/main/java/org/folio/calendar/domain/mapper/ExceptionRangeMapper.java
src/main/java/org/folio/calendar/domain/mapper/NormalOpeningMapper.java
src/main/java/org/folio/calendar/service/CustomTenantService.java
src/main/java/org/folio/calendar/utils/DateUtils.java
src/main/java/org/folio/calendar/utils/PeriodUtils.java
src/test/java/org/folio/calendar/integration/migration/NormalMigrationTest.java
src/test/java/org/folio/calendar/testconstants/Calendars.java
src/test/java/org/folio/calendar/testconstants/ExceptionRanges.java
src/test/java/org/folio/calendar/testconstants/Periods.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsCalendarConversionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsConflictedOrphanExceptionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsExceptionalCalendarConversionTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsExceptionalTest.java
src/test/java/org/folio/calendar/unit/utils/PeriodUtilsNullConversionTest.java
src/test/resources/database-migrate-data.sql

Duplicate of #159 but to be merged into master for Orchid release.

MODCAL-124: Fix issue with legacy exceptions not associating with calendars

---

descriptors/ModuleDescriptor-template.json

Ref [MODCAL-128](https://issues.folio.org/browse/MODCAL-128).

MODCAL-128: Update docker image specifier

---

pom.xml

https://wiki.folio.org/display/TC/Poppy#Poppy-Frameworks.1
This will also fix multiple security issues in the dependencies:
https://nvd.nist.gov/vuln/detail/CVE-2023-20873
https://nvd.nist.gov/vuln/detail/CVE-2023-20860
https://nvd.nist.gov/vuln/detail/CVE-2023-20883
https://nvd.nist.gov/vuln/detail/CVE-2022-41946
https://nvd.nist.gov/vuln/detail/CVE-2023-3635
https://nvd.nist.gov/vuln/detail/CVE-2023-41080
https://nvd.nist.gov/vuln/detail/CVE-2023-20863
https://nvd.nist.gov/vuln/detail/CVE-2023-28709
https://nvd.nist.gov/vuln/detail/CVE-2023-28708
https://nvd.nist.gov/vuln/detail/CVE-2023-20861
https://nvd.nist.gov/vuln/detail/CVE-2023-2976

MODCAL-129: Upgrade dependencies (Spring, ...) for Poppy

---

descriptors/ModuleDescriptor-template.json

Updated mod-descriptor to phase out vestigial "calendar.endpoint.dates.get"

Fixed issues arising from MODCAL-136
